#!/bin/bash -ex

echo "Job workspace $1"
echo "OS type $2"

function run_with_xvfb() {
    eval $@
}

function terminate_xvfb() {
  if [ $(command -v xvfb-run) ]; then
    echo Stopping Xvfb
  fi
}

#run_with_xvfb $1/jenkins/test_runner.bat
#terminate_xvfb
mkdir -p build/Testing
cp $1/jenkins/unittest-$2.xml build/Testing/
