#!/bin/bash -ex

echo "Job workspace $1"
echo "OS type $2"

function run_with_xvfb() {
    if [[ $OSTYPE == "msys"* ]]; then
        cmd //C "start /B /WAIT $@"
    else
       eval $@
    fi
}

function terminate_xvfb() {
  if [ $(command -v xvfb-run) ]; then
    echo Stopping Xvfb
  fi
}

run_with_xvfb $1/jenkins/test_runner.bat
terminate_xvfb
